version: "3.7"

services:
        oslp:
                build: .
                tmpfs:
                        - /tmp
                        - /run
                        - /run/lock
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                        - /etc/timezone:/etc/timezone:ro
                        - $XAUTHORITY:/root/.Xauthority:ro
                        - oslp_home:/root:rw
                        - ${OSLPCONF:-/dev/null}:/etc/environment.d/99-oslp.conf:ro
                        - ${OSLPCONF:-/dev/null}:/etc/bash.bashrc:ro
                environment:
                        - container=docker
                        - QT_X11_NO_MITSHM=1
                        - TZ=EST5EDT
                hostname: oslp
                container_name: oslp
                ipc: host
                network_mode: host
                stop_signal: SIGRTMIN+3
                ulimits:
                        memlock: 400000000
                        rtprio: 90
                devices:
                        - /dev/snd
                        - /dev/dri
                tty: true
                command: /bin/systemd
volumes:
        oslp_home:



