#! /bin/bash

# Run JALV for the given synth.

# $1: JSON directory
# $2: JSON file to process

[ -z "$2" ] && exit

uri=`jq '.[].uri|select(. != null)' "$1/$2" | tr -d '"'`

client=`jq '.[].client|select(. != null)' "$1/$2" | tr -d '"'`

# Prepend -c to each setting

stgs=`jq -r ".[].settings|map(\"-c \"+.)[]" "$1/$2"`

guifl=""
jalvx=""

[ ! -z "$DISPLAY" ] && {
	guifl="-s"
	jalvx=".gtk3"
} || {
	guifl="-o"
}

[ -z "$uri" ] && { 
	echo "Plugin URI not specified"
	exit 1
}

[ -z "$client" ] && { 
	echo "JACK client name not specified"
	exit 1
}

loadfl=""
loaddir=""

[ -f "${OSLP_SAVED_STATE_PATH}/${client}/state.ttl" ] && {
	loadfl="-l"
	loaddir="${OSLP_SAVED_STATE_PATH}/$client"
} || mkdir -p "${OSLP_SAVED_STATE_PATH}/$client"

jalv${jalvx} $guifl -n "$client" -x $stgs "$loadfl" "$loaddir" "$uri" < "/tmp/${client}.in" > /dev/null

